services:
  db:
    image: postgres:14
    env_file: .env
    expose:
      - '5432'
    volumes:
      - feast-finder:/var/lib/postgresql/data
      - ./src/init_data:/docker-entrypoint-initdb.d

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  web:
    image: node:lts
    user: 'node'
    working_dir: /repository
    env_file: .env
    environment:
      - NODE_ENV=development
    depends_on:
      - db
      - redis
    ports:
      - '80:3000'
    volumes:
      - ./:/repository
    command: 'npm start'
volumes:
  feast-finder:
