services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-testdb}
      POSTGRES_USER: ${POSTGRES_USER:-testuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-testpass}
    volumes:
      - postgres_data_test:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  web:
    image: node:lts
    working_dir: /repository
    environment:
      NODE_ENV: test
      SESSION_SECRET: ${SESSION_SECRET}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - db
      - redis
    ports:
      - '80:3000'
    volumes:
      - .:/repository
    command: sh -c "npm install && npm test"

volumes:
  postgres_data_test: