name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Run tests using Docker Compose
      env:
        SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
        POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      run: |
        docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit --exit-code-from web

    - name: Docker Compose Down
      if: always() # Ensure cleanup runs even if tests fail
      run: docker-compose -f docker-compose.test.yml down -v --remove-orphans