name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/*] # Specify the LTS version of Node.js to test against

    steps:
    - uses: actions/checkout@v4 # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm' # Optional: Caches npm dependencies
    - run: npm ci # Installs dependencies using package-lock.json
    - run: npm run build --if-present # Optional: Runs a build script if it exists
    - run: npm test # Runs tests