name: Git Pull on Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 20.3.255.58 >> ~/.ssh/known_hosts

      - name: Check for changes in README or Handlebars/HTML files
        id: file-check
        run: |
          git diff --name-only HEAD^ HEAD > changed_files.txt
          if grep -E "README.md|.*\\.html|.*\\.handlebars" changed_files.txt; then
            echo "skip-deploy=true" >> $GITHUB_ENV
          fi

      - name: Trigger git pull on server
        if: env.skip-deploy != 'true'
        run: |
          ssh feast@20.3.255.58 <<EOF
            cd /home/feast/Feast-Finder
            git pull origin main
            sudo docker compose down
            sudo docker compose up -d
          EOF
