name: Git Pull on Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 20.3.255.58 >> ~/.ssh/known_hosts

      - name: Trigger git pull on server
        run: |
          ssh feast@20.3.255.58 <<EOF
            cd /home/feast/Feast-Finder
            git pull origin main
          EOF
